name: Dependabot PR Manager
author: eamonnk418
description: Approve and auto-merge Dependabot pull requests selectively based on metadata and update type.
inputs:
  github-token:
    required: true
    description: "GitHub token for authentication."
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Fetch Metadata from Dependabot PRs
      if: ${{ github.event.sender.type == 'Bot' && github.event.pull_request.user.login == 'dependabot[bot]' }}
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
      with:
        alert-lookup: true
        compat-lookup: true
        github-token: ${{ inputs.github-token }}
    - name: Add a label for all production dependencies
      if: ${{ steps.metadata.outputs.dependency-type == 'direct:production' }}
      run: gh pr edit "$PR_URL" --add-label "production"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
      shell: bash
    - name: Add a label for all development dependencies
      if: ${{ steps.metadata.outputs.dependency-type == 'direct:development' }}
      run: gh pr edit "$PR_URL" --add-label "development"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
      shell: bash
