name: CI

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '**/*.md'
  pull_request:
    branches: 
      - main
    paths-ignore: 
      - '**/*.md'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Dependabot PR Manager Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-commit-verification: "true"
          skip-verification: "true"
