name: CI

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '**/*.md'
  pull_request:
    branches: 
      - main
    paths-ignore: 
      - '**.md'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action
        uses: ./
        
