name: Dependabot Pull Request

on: pull_request

jobs:
  dependabot:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot PR Manager
        uses: eamonnk418/dependabot-pr-manager-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
