name: Dependabot PR Manager

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot PR Manager
        uses: eamonnk418/dependabot-pr-manager-action@v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
