name: Release

on:
 push:
    branches:
      - main
    paths-ignore: 
      - '.github/dependabot.yml'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Semantic Release
        uses: go-semantic-release/action@v1.23.0
        id: semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
