name: Release

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Semantic Release
        uses: go-semantic-release/action@v1.22.0
        id: semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
