name: Dependabot Pull Request

on: 
  workflow_call: 
    secrets:
      github-token:
        required: true
        description: "GitHub token for authentication."

jobs:
  pr-manager:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot PR Manager
        uses: eamonnk418/dependabot-pr-manager-action@main
        with:
          github-token: ${{ secrets.github-token }}
